%YAML:1.0

dataset_dir: /home/libo/slam_work/final_project/data_set_gray/00

#camera intrinsics
camera.fx: 517.3
camera.fy: 516.3
camera.cx: 325.1
camera.cy: 249.7

num_features: 150
num_features_init: 50
num_features_traking: 50